# -*- coding: utf-8 -*-
"""Custom_training_Dectectron2_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmwNoboZbnyTgPCkkwnh8QxhnlMlXMAJ

## Custom Dataset Training with Detectron2

---
"""

!nvidia-smi

!pip install roboflow

!python -m pip install pyyaml==5.1
import sys, os, distutils.core

!git clone 'https://github.com/facebookresearch/detectron2'
dist=distutils.core.run_setup("./detectron2/setup.py")
!python -m pip install {' '.join([f"'{x}'" for x in dist.install_requires])}
sys.path.insert(0, os.path.abspath('./detectron2'))

import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog

from roboflow import Roboflow
rf = Roboflow(api_key="DWkhqBMU6VvWaP5Glt64")
project = rf.workspace("university-bswxt").project("crack-bphdr")
version = project.version(2)
dataset = version.download("coco-segmentation")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/crack-2/

!pwd

from detectron2.data.datasets import register_coco_instances
register_coco_instances("exp_train", {}, "/content/crack-2/train/_annotations.coco.json","./train")
register_coco_instances("exp_valid", {}, "/content/crack-2/vaid/_annotations.coco.json","./valid")
register_coco_instances("exp_test", {}, "/content/crack-2/test/_annotations.coco.json","./test")

sample_metadata = MetadataCatalog.get("exp_train")
dataset_dicts = DatasetCatalog.get("exp_train")

"""### Visualize Training data"""

my_dataset_train_metadata = MetadataCatalog.get("exp_train")
dataset_dicts = DatasetCatalog.get("exp_train")

import random
from detectron2.utils.visualizer import Visualizer

for d in random.sample(dataset_dicts, 5):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=my_dataset_train_metadata, scale=0.5)
    vis=visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])

from detectron2.engine import DefaultTrainer

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("exp_train")
cfg.DATASETS.TEST = ("exp_valid")
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.0025  # pack a good LR
cfg.SOLVER.MAX_ITER = 1000
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg.DATASETS.TEST = ("exp_test", )
predictor = DefaultPredictor(cfg)

from detectron2.utils.visualizer import ColorMode
import os
import cv2

for d in os.listdir("test"):
  image_path=os.path.join("test", d)
  im = cv2.imread(image_path)

  if im is None:
    print(f"warning: could not read image at path: {image_path}")
    continue

  outputs = predictor(im)
  v = Visualizer(im[:, :, ::-1],
                metadata=sample_metadata,
                scale=0.8,
                instance_mode=ColorMode.IMAGE_BW)  # remove the color
  v=v.draw_instance_predictions(outputs["instances"].to("cpu"))
  cv2_imshow(v.get_image()[:, :, ::-1])

from detectron2.utils.visualizer import ColorMode

for d in random.sample(dataset_dicts, 4):
  im = cv2.imread(d["file_name"])
  outputs = predictor(im)
  v = Visualizer(im[:, :, ::-1],
                metadata=sample_metadata,
                scale=0.8,
                instance_mode=ColorMode.IMAGE_BW)  # remove the color
  v=v.draw_instance_predictions(outputs["instances"].to("cpu"))
  cv2_imshow(v.get_image()[:, :, ::-1])

from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("exp_test", cfg, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "exp_test")
print(inference_on_dataset(trainer.model, val_loader, evaluator))

f=open('config.yml', 'w')
f.write(cfg.dump())
f.close()

