# -*- coding: utf-8 -*-
"""Inferencing with Pretrained YOLO Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loueq-RRAWP3Qnm_Z0oWAD2Q3jcrf8QF

# Inferencing with Pretrained YOLO Models

### Installing Ultralytics
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

"""### Command Line Interface"""

# Visualize the predicted image function

import cv2
from google.colab.patches import cv2_imshow

def show_image(image_path):
  image = cv2.imread(image_path)
  if image is None:
    print("Error: Image not found!")
    return

  cv2_imshow(image)

# Run inference on an image with YOLO1n

!yolo predict model = yolo11n.pt source = 'https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg'

show_image('/content/runs/detect/predict/pexels-photo-13872248.jpg')

!yolo predict model = yolo11s.pt source = 'https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg'

!yolo predict model = yolo11m.pt source = 'https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg'

!yolo predict model = yolo11l.pt source = 'https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg'